apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hw3o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hw3o
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hw3o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hw3o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hw3o
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ogio-tenant/rhtap-demo-app/hacbs-test-project-hw3o@sha256:7caec9c7d45b6583f4b3a6969a75eaca801ef731afd34e2fe9590e54b9f64ccd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
