apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hw3o
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ogio-tenant/rhtap-demo-app/hacbs-test-project-hw3o@sha256:7caec9c7d45b6583f4b3a6969a75eaca801ef731afd34e2fe9590e54b9f64ccd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
